#! /bin/sh
sxhkd &
polybar myBar &
nm-applet &
#emacs --daemon &
numlockx &
xsetwacom set  "Wacom Bamboo One S Pen stylus" PressureCurve 0 15 85 100 &
seafile-applet &
sct 3500 &

#if [[ $(hostname) == 'nixos' ]]; then
	bspc monitor -d I II III IV V VI VII VIII IX X

	/home/user/dotfiles/common/scripts/monitor-hotplug.sh
	#elif [[ $(hostname) == 'nixos-tower' ]]; then
#	xrandr --output DP-0 --off --output DVI-I-1 --off --output DVI-I-0 --off --output DP-1 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output HDMI-0 --mode 1920x1080 --pos 2560x0 --rotate normal
#	bspc monitor DP-1 -d I II III IV V
#	bspc monitor HDMI-0 -d VI VII VIII IX X
#elif [[ $(hostname) == 'nixos-p50' ]]; then
#	bspc monitor -d I II III IV V VI VII VIII IX X
#elif [[ $(hostname) == 'nixos-t470' ]]; then
#	#xrandr --output VIRTUAL1 --off --output eDP1 --mode 1920x1080 --pos 2560x0 --rotate normal --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
#	xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
#	#bspc monitor DP2-2 -d I II III IV V VI
#	bspc monitor -d I II III IV V VI VII VIII IX X
#	#bspc monitor eDP1 -d VII VIII IX X
#fi


bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc merge_overlapping_monitors true

bspc config normal_border_color
bspc config active_border_color  \#145f9d
bspc config focused_border_color \#145f9d

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled
