#! /bin/sh
sxhkd &
polybar myBar &
nm-applet &
#emacs --daemon &
numlockx &
xsetwacom set  "Wacom Bamboo One S Pen stylus" PressureCurve 0 15 85 100 &
seafile-applet &
sct 3500 &

bspc monitor -d I II III IV V VI VII VIII IX X
/home/user/dotfiles/common/scripts/monitor-hotplug.sh

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc merge_overlapping_monitors true

bspc config normal_border_color
bspc config active_border_color  \#145f9d
bspc config focused_border_color \#145f9d

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a zatharu state=tiled
